### ISSUE TITLE
print preview

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal-gtk#105]
The print portal dialog should offer a preview option

**Comment by ManIVIctorious** [comment]
Recently, I was doing a lot of scanning and printing and was very surprised to find no print-preview in the evince flatpak. Since I could remember that that functionality was there (at least a few years back in a non flatpak) I was very surprised by this issue.

After installing the exact same version of evince directly from the repositories I realised that the print-preview suddenly was there, found this closed issue and skimmed through old commit messages to find out that the `evince-previewer` application has to be present on the execution path.

Although I realised a little bit later that this information was available when looking in the  package information of xdg-desktop-portal-gtk, I would call this rather well hidden. Additionally, this has the unfortunate effect, that for a working print-preview it is necessary to install the system evince package. Hence, to get a print-preview in the evince flatpak (undoubtedly one of the applications benefiting most from this functionality) one has to install the system evince package which, at least in my opinion, is rather odd.

Therefore, I wanted to ask you if it is ever planned to move the evince-previewer application into `xdg-desktop-portal-gtk`. From a packaging point of view, evince could rely on xdg-desktop-portal and use the print-preview provided there. IMHO this would yield the potential to simplify the printer-portal code (maybe setting the preview unconditionally to true) and would result in a much cleaner separation of system and applications.

Hopefully, I didn't offend you by commenting on such an old issue and sincerely hope you consider this proposal.
