### ISSUE TITLE
wallpaper: preview mismatch

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal-gtk#264]
![Screenshot from 2019-12-10 11-27-38](https://user-images.githubusercontent.com/4834845/70548391-71d71780-1b40-11ea-92c5-ab31231dff08.png)

As you can see, the preview does not match the end result - it is cropped differently

**Comment by felipeborges** [comment]
I wonder if it would be interesting to offer an API in the key-value options parameter where users could pass the desired $picture-options (mapped to the GNOME ones): none, wallpaper, centered, scaled, stretched, zoom, spanned.

Or we could just be consistent with what GNOME Settings does, which is 'zoom'.

Thoughts?

**Comment by matthiasclasen** [comment]
I'm not too hot on exposing those tweaky details in the UI - we've taken all that out of the background settings long ago. Adding options in the api would perhaps be harmless. But I don't think it is important or relevant for this issue.

My main concern is that the preview should present the image as it will appear on the desktop.

**Comment by hadess** [comment]
The code in `wallpaper.c` doesn't touch any settings but the URI, so if I have the placement set to tiled, then it's not going to look the same because the code in `wallpaperpreview.c` does:
```
gnome_bg_set_placement (self->bg, G_DESKTOP_BACKGROUND_STYLE_STRETCHED);
```

I think that both the preview and the code to set it should use `G_DESKTOP_BACKGROUND_STYLE_ZOOM` as the placement, it's the one used in the background panel for picture files.

**Comment by matthiasclasen** [comment]
have a patch? that would be excellent

**Comment by hadess** [comment]
Done in https://github.com/flatpak/xdg-desktop-portal-gtk/pull/294
