### ISSUE TITLE
GTK3 file chooser instead of GTK4 one on sway

### ISSUE THREAD

**Issue by phisch** [flatpak/xdg-desktop-portal-gtk#475]
I'm using the [sway compositor](https://github.com/swaywm/sway), and noticed that this portal always shows the GTK3 file chooser instead of the GTK4 one.

What decides which one to show? Is there some way to control this?

I couldn't find documentation or information on this. Would be nice to get some clarity on this!

**Comment by ebassi** [comment]
The GTK portal uses GTK3, not GTK4, as it's the "portal of last resort".

If you want to use GTK4 you will need to either use GNOME, or write a new portal implementation that uses GTK4.

**Comment by phisch** [comment]
Got it, thanks for the explanation! :+1:

**Comment by WavyEbuilder** [comment]
> The GTK portal uses GTK3, not GTK4, as it's the "portal of last resort".

Pardon my ignorance, but is there a specific reason for choosing GTK3 over GTK4 for the portal of last resort? I can absolutely understand the choice to not use libadwaita for a more "generic" fallback portal, but I don't see why not GTK4.

> If you want to use GTK4 you will need to either use GNOME, or write a new portal implementation that uses GTK4.

Is this specific repo open a GTK4 port?

**Comment by TingPing** [comment]
> Pardon my ignorance, but is there a specific reason for choosing GTK3 over GTK4 for the portal of last resort? I can absolutely understand the choice to not use libadwaita for a more "generic" fallback portal, but I don't see why not GTK4.

Most of this project is approaching 10 years old, this was well before GTK4 was released. `xdg-desktop-portal-gnome` came around later and since it was targeting GNOME used libadwaita/gtk4.

Since this project was already stable I think there had to be a strong reason to move it to GTK4. I think, at least years ago, the community sentiment for a lot of non-gnome desktops was pro-GTK3, as it was just the more common and mature choice for them.

Since years have passed and GTK4 has stabilized maybe its worth discussing. I think the first thing to know is who is volunteering to do this. Then answer what do users gain by this move.

**Comment by ebassi** [comment]
Moving to GTK4 would imply having a file chooser dialog inside the xdp-gtk portal itself, since GTK4 deprecated `GtkFileChooserDialog`. That adds another level of complexity to the maintenance of what is supposed to be a generic portal backend.

**Comment by WavyEbuilder** [comment]
> Moving to GTK4 would imply having a file chooser dialog inside the xdp-gtk portal itself, since GTK4 deprecated `GtkFileChooserDialog`. That adds another level of complexity to the maintenance of what is supposed to be a generic portal backend.

Is there not https://docs.gtk.org/gtk4/class.FileDialog.html now? Granted, never attempted to use it myself, but the docs for `GtkFileChooserDialog` indicate `GtkFileDialog` is the suggested replacement:

> Use [GtkFileDialog](https://docs.gtk.org/gtk4/class.FileDialog.html) instead.

**Comment by ebassi** [comment]
`GtkFileDialog` is an object that calls the platform's specific file selection dialog, and that means calling the file chooser portal on Linux. The portal backend cannot use `GtkFileDialog` since it's the one providing that dialog; as I said, the GTK portal backend would need to copy the various components of the `GtkFileChooserDialog` out of GTK and into the portal backend itself.
