### ISSUE TITLE
Input Capture Support 

### ISSUE THREAD

**Issue by sithlord48** [flatpak/xdg-desktop-portal-gtk#494]
Input capture is need to support applications like [input-leap](https://github.com/input-leap/input-leap) , and [deskflow](https://github.com/deskflow/deskflow) (formally synergy).

Support has added in the KDE and GNOME portals.
I am raising this issue in portals without support.  

The portal should also allow input capture access to the clipboard.

**Comment by smcv** [comment]
I believe input capture is considered to be out-of-scope for this last-resort portal implementation. Desktop environments that wish to support input capture should provide their own portal backend that provides it, instead of relying on this one.

For example, GNOME uses `xdg-desktop-portal-gnome` for input capture functionality.

**Comment by sithlord48** [comment]
Thank you for your response

**Comment by jadahl** [comment]
Indeed - out of scope for xdg-desktop-portal-gtk.
